name: Test and release

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Test
        run: make test GO111MODULE=on

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --release-notes <(git tag -l --format='%(tag) (%(taggerdate:short))' $GITHUB_REF ; git tag -l --format='%(body)' $GITHUB_REF)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
